### ISSUE TITLE
Reset user session

### ISSUE THREAD

**Issue by DanielePalombo** [nebulab/solidus_square#30]
ref https://github.com/nebulab/solidus_square/issues/26

When the user lands to the redirectURL specified on configuration, we should show a thank you message and reset his session, in order to avoid that he will make any other changes to the order.

I'm not sure if it would be better to remove the user from the order or if it will be enough to link a new order to the user.

**Comment by garciajordy** [comment]
A simple `reset_session` would do the trick I guess?

**Comment by kennyadsl** [comment]
@garciajordy I don't think so, because the order can be accessed via API as well. We need to be sure that a user logged in with the API (with the `Authorization` Header) will see their [current order](https://solidus.docs.stoplight.io/api-reference/orders/get-current-order) empty after the order is completed on Square.

**Comment by DanielePalombo** [comment]
I spoke with @kennyadsl IRL and we agreed that the best way to handle it would be to create a new empty cart linked to the current user. 

So the previous order will stay in the system waiting to be processed by the webhook.
The new order will be the current order of the user.
